<!DOCTYPE html>
<html lang="<?php echo LANG_ID?>">
<head>
  <?php echo $this->headTitle().PHP_EOL; ?>
  <meta charset="utf-8" />
  <meta name="author" content="Oloma Software">
  <?php echo $this->headMeta().PHP_EOL; ?>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <?php echo $this->headLink().PHP_EOL; ?>
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <script type="module" crossorigin src="/assets/index-Cvr9Cg4r.js?v=1"></script>
  <link rel="stylesheet" crossorigin href="/assets/index-MLZPbzUm.css?v=13">
  <!-- Favicon -->
  <link rel="apple-touch-icon" sizes="120x120" href="/assets/favicon/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon/favicon-16x16.png">
  <link rel="manifest" href="/assets/favicon/site.webmanifest">
  <link rel="mask-icon" href="/assets/favicon/safari-pinned-tab.svg" color="#0a7248">
  <meta name="msapplication-TileColor" content="#0a7248">
  <meta name="theme-color" content="#ffffff">
  <link rel="shortcut icon" href="/assets/favicon/favicon.ico" type="image/x-icon" />
  <link rel="stylesheet" type="text/css" href="/assets/css/prism/prism.css?v=4" />
  <?php echo $this->headScript().PHP_EOL; ?>
</head>

<body class="bg-light" 
    data-prismjs-copy="Copy"
    data-prismjs-copy-error="Press Ctrl+C to copy"
    data-prismjs-copy-success="Copied !">

  <!-- NAVBAR -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top bg-white border-bottom">
    <div class="container-fluid">
      <!-- Brand -->
      <div class="ps-2">
        <a class="navbar-brand" href="/">
          <strong>Olodoc</strong>
        </a>
      </div>

      <!-- Toggler -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <svg xmlns="http://www.w3.org/2000/svg" height="32px" width="32px" viewBox="0 -960 960 960" fill="currentColor"><path d="M120-240v-80h720v80H120Zm0-200v-80h720v80H120Zm0-200v-80h720v80H120Z"/></svg>
      </button>

      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708"/>
          </svg>
        </button>

        <!-- Navigation -->
        <ul class="navbar-nav ms-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="/index.html" id="navbarLanguages" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <?php echo $this->translate("Languages")?>
            </a>
            <div class="dropdown-menu dropdown-menu-md" aria-labelledby="navbarLanguages" data-bs-popper="none">
              <div class="list-group list-group-flush">
                  <!-- Link -->
                  <?php echo AVAILABLE_LANGUAGES ?> 
              </div>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarSupport" data-bs-toggle="dropdown" href="#" aria-haspopup="true" aria-expanded="false">
              <?php echo $this->translate("Support")?>
            </a>
            <div class="dropdown-menu dropdown-menu-md" aria-labelledby="navbarSupport">
              <div class="list-group list-group-flush">
                <a class="list-group-item" href="https://github.com/olomadev/olodoc/issues/new/choose" target="_blank" >
                  <!-- Icon -->
                  <div class="icon icon-sm text-primary">
                    <svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#000000"><path d="M880-80 720-240H320q-33 0-56.5-23.5T240-320v-40h440q33 0 56.5-23.5T760-440v-280h40q33 0 56.5 23.5T880-640v560ZM160-473l47-47h393v-280H160v327ZM80-280v-520q0-33 23.5-56.5T160-880h440q33 0 56.5 23.5T680-800v280q0 33-23.5 56.5T600-440H240L80-280Zm80-240v-280 280Z"/></svg>
                  </div>
                  <!-- Content -->
                  <div class="ms-4">
                    <!-- Heading -->
                    <div class="fw-bold text-primary mb-1">
                      <?php echo $this->translate("Create a New Entry")?>
                    </div>
                    <!-- Text -->
                    <p class="fs-sm mb-0 text-muted">
                      <?php echo $this->translate("Create bug report, Feature request or  Support question")?>
                    </p>
                  </div>
                </a>
              </div>
            </div>
          </li>
        </ul>

        <ul class="navbar-btn navbar-nav ms-auto pe-3">
          <li class="nav-item dropdown">
          <?php if (! empty($this->placeholder("user")[0])) { ?>
            <a class="nav-link dropdown-toggle btn btn-sm btn-primary" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
              </svg> &nbsp;<?php echo $this->placeholder("user")[0]->getDetails()['fullname']; ?>
              </a>
              <div class="dropdown-menu">
                  <div class="container-fluid">
                    <a class="dropdown-item navbar-btn btn btn-sm btn-secondary" onclick="crossDomainLogout();" style="padding: 15px;">
                      <?php echo $this->translate("Logout")?>
                    </a>
                  </div>
                  <!-- <div class="dropdown-divider"></div> -->
              </div>
          <?php } else { ?>

            <a class="nav-link dropdown-toggle btn btn-sm btn-primary" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><?php echo $this->translate("Login to My Account")?></a>

            <div class="dropdown-menu">
              <a class="dropdown-item navbar-btn btn btn-sm btn-secondary mb-2" href="javascript:void(0);" onclick="socialiteLogin('github')" style="padding: 15px;">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                  <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8"></path>
                </svg> <?php echo $this->translate("Sign in with Github")?>
              </a>
              <a class="dropdown-item navbar-btn btn btn-sm btn-secondary mb-2" href="javascript:void(0);" onclick="socialiteLogin('google')" style="padding: 15px;">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-google" viewBox="0 0 16 16">
                  <path d="M15.545 6.558a9.42 9.42 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.689 7.689 0 0 1 5.352 2.082l-2.284 2.284A4.347 4.347 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.792 4.792 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.702 3.702 0 0 0 1.599-2.431H8v-3.08h7.545z"/>
                </svg> <?php echo $this->translate("Sign in with Google")?>
              </a>

              <a class="dropdown-item navbar-btn btn btn-sm btn-secondary" href="javascript:void(0);" onclick="classicLogin()" style="padding: 15px;">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                </svg> &nbsp;<?php echo $this->translate("Classic Login")?>
              </a>
              <!-- <div class="dropdown-divider"></div> -->
            </div>
          <?php } ?>
          </li> 
      </ul>

      </div>
    </div>
  </nav>

  <!-- BREADCRUMB -->
  <nav class="sub-navbar mt-lg-5 d-lg-none">
    <div class="container-fluid document-content">
      <div class="row align-items-center pt-2">
        <div class="col">
          <!-- Breadcrumb -->
          <?php echo $this->placeholder('breadCrumbsMobile') ?>
        </div>
        <div class="col-auto">

            <!-- Toggler -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#sidenavCollapse" aria-controls="sidenavCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#000000"><path d="M120-240v-80h720v80H120Zm0-200v-80h720v80H120Zm0-200v-80h720v80H120Z"/></svg>
            </button>

        </div>
      </div> <!-- / .row -->
    </div> <!-- / .container -->
  </nav>

<?php echo $this->content ?>

<!-- JAVASCRIPT -->
<script src="/assets/js/axios.min.js"></script>
<script src="/assets/js/prism/prism.js?v=4"></script>
<!-- This fixes the line highlight wrong number hilite bug -->
<script src="/assets/js/prism/prism-line-highlight.js?v=4"></script>
<script src="/assets/js/anchor.min.js"></script>
<script src="/assets/js/app.js?v=21"></script>
<script type="text/javascript">     
  anchors.add(); // The default instance.
  <?php
      if (! empty($this->placeholder('pageJavascript')[0])) {
            echo $this->placeholder('pageJavascript')[0];
      }
  ?>
</script>
</body>
</html>